name: Build and Deploy Code

# on: 
#   push:
#     branches: 
#       - "main"
#   pull_request:
#     branches:
#       - "test_branch"

# trigger action on push or pull request
on: [push, pull_request]

# create the job upon initial trigger
jobs:
  job1:
    runs-on: ubuntu-ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2 # from checkout github marketplace
      - name: say hi to adnan
        run: echo "hello adnan"
